name: Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 21 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container: alpine:latest
    steps:
    - uses: actions/checkout@v4

    - name: build
      if: always()
      run: |
        apk add bash \
          bash \
          bison \
          build-base \
          cairo-dev \
          check-dev \
          coreutils \
          cppcheck \
          flex \
          gdk-pixbuf-dev \
          git \
          glib-dev \
          gvfs \
          librsvg-dev \
          libxcb-dev \
          libxkbcommon-dev \
          meson \
          musl-fts-dev \
          pango-dev \
          patchelf \
          ronn \
          startup-notification-dev \
          strace \
          wget \
          xcb-util-cursor-dev \
          xcb-util-dev \
          xcb-util-keysyms-dev \
          xcb-util-wm-dev \
          xcb-util-xrm-dev \
          xkeyboard-config-dev

        chmod +x ./rofi-appimage.sh && ./rofi-appimage.sh
        mkdir dist
        mv *.AppImage* dist/

    - name: Check version file
      run: |
       cat ~/version
       echo "APP_VERSION=$(cat ~/version)" >> "${GITHUB_ENV}"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: AppImage
        path: 'dist'
        
    - name: Upload version file
      uses: actions/upload-artifact@v4.6.2
      with:
       name: version
       path: ~/version
    
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4.1.9
          with:
            name: AppImage
        - uses: actions/download-artifact@v4.1.9
          with:
            name: version

        - name: Read version and Get date
          run: |
            echo "VERSION=$(cat version)" >> "${GITHUB_ENV}"
            echo "DATE=$(date +'%Y-%m-%d_%s')" >> "$GITHUB_ENV"

        - name: Release Artifacts
          uses: softprops/action-gh-release@v2.2.2
          with:
            name: "rofi: ${{ env.VERSION }}"
            tag_name: "${{ env.VERSION }}@${{ env.DATE }}"
            prerelease: false
            draft: false
            generate_release_notes: false
            fail_on_unmatched_files: false
            make_latest: true
            files: |
              *.AppImage*
